name: Build and Test

on: [ push ]
jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        run: sudo apt-get install ninja-build
      - name: Install OpenCV dependencies
        run: |
          sudo apt install -y build-essential pkg-config \
          libjpeg-dev libpng-dev libtiff-dev \
          libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
          libxvidcore-dev libx264-dev \
          libgtk-3-dev \
          libatlas-base-dev gfortran  


      - uses: Dovyski/setup-opencv-action@v1.1
        with:
          opencv-version: 4.0.0
          install-deps: false
          opencv-extra-modules: false
          ENABLE_PRECOMPILED_HEADERS: ON
          INSTALL_C_EXAMPLES: OFF
          BUILD_EXAMPLES: OFF
      - name: Configure CMake and build
        run: |
          mkdir build
          cd build
          cmake -DENABLE_TESTING=ON -G Ninja ..
          ninja
      - name: Run tests
        run: ctest --output-on-failure --test-dir build/tests

#  sudo apt install -y ninja-build
