name: Build and Test

on: [push]
jobs:
  linux:
    runs-on:
      - ubuntu-latest
  timeout-minutes: 60
  steps:
    - uses: actions/checkout@v4
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - uses: Dovyski/setup-opencv-action@v1.1
      with:
        opencv-version: 4.0.0
        opencv-extra-modules: false
        ENABLE_PRECOMPILED_HEADERS: ON
        INSTALL_C_EXAMPLES: OFF
        BUILD_EXAMPLES: OFF
    - name: Configure CMake and build
      run: |
        mkdir build
        cd build
        cmake -DENABLE_TESTING=ON -G Ninja ..
        ninja
    - name: Run tests
      run: ctest -V

